/**
 * Nyuchi Platform - Database Types
 * "I am because we are"
 *
 * These types will be generated by Supabase CLI once migrations are run.
 * For now, we define the core structure manually.
 */

/**
 * User role enum (primary role)
 */
export type UserRole = 'user' | 'contributor' | 'moderator' | 'reviewer' | 'admin';

/**
 * User capabilities (can hold multiple)
 * - contributor: Can submit content
 * - expert: Registered as local expert
 * - business_owner: Has business listings
 * - moderator: Reviews content submissions
 * - reviewer: Reviews expert/business applications
 * - admin: Full access to all pipelines
 */
export type UserCapability = 'contributor' | 'expert' | 'business_owner' | 'moderator' | 'reviewer' | 'admin';

/**
 * Submission type enum
 */
export type SubmissionType = 'content' | 'expert_application' | 'business_application' | 'directory_listing' | 'travel_business';

/**
 * Pipeline status enum (unified across all submission types)
 */
export type PipelineStatus = 'draft' | 'submitted' | 'in_review' | 'needs_changes' | 'approved' | 'rejected' | 'published';

/**
 * Listing status enum
 */
export type ListingStatus = 'draft' | 'pending' | 'approved' | 'rejected' | 'published';

/**
 * Content status enum
 */
export type ContentStatus = 'draft' | 'submitted' | 'reviewing' | 'approved' | 'rejected' | 'published';

/**
 * Verification status enum
 */
export type VerificationStatus = 'none' | 'pending' | 'approved' | 'rejected';

/**
 * Subscription status enum
 */
export type SubscriptionStatus = 'active' | 'canceled' | 'past_due' | 'trialing' | 'incomplete';

/**
 * Application status enum (for experts and businesses)
 */
export type ApplicationStatus = 'pending' | 'approved' | 'rejected';

/**
 * Listing type enum (for business partners)
 */
export type ListingType = 'free' | 'verified' | 'premium';

/**
 * Expert category enum
 */
export type ExpertCategory = 'safari_guide' | 'cultural_specialist' | 'adventure_guide' | 'urban_guide' | 'photography_guide' | 'bird_guide';

/**
 * Activity type enum (for audit logging)
 */
export type ActivityType =
  | 'SIGN_UP'
  | 'SIGN_IN'
  | 'SIGN_OUT'
  | 'UPDATE_PASSWORD'
  | 'DELETE_ACCOUNT'
  | 'UPDATE_ACCOUNT'
  | 'CREATE_CONTENT'
  | 'UPDATE_CONTENT'
  | 'DELETE_CONTENT'
  | 'SUBMIT_CONTENT'
  | 'APPROVE_CONTENT'
  | 'REJECT_CONTENT'
  | 'CREATE_LISTING'
  | 'UPDATE_LISTING'
  | 'DELETE_LISTING'
  | 'APPLY_EXPERT'
  | 'APPLY_BUSINESS'
  | 'VERIFY_BUSINESS'
  | 'EARN_UBUNTU_POINTS'
  | 'SUBSCRIBE'
  | 'UNSUBSCRIBE';

/**
 * JSON value type for metadata
 */
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

/**
 * Database tables
 */
export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          company: string | null;
          country: string | null;
          role: UserRole;
          capabilities: UserCapability[];
          ubuntu_score: number;
          contribution_count: number;
          stripe_customer_id: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          company?: string | null;
          country?: string | null;
          role?: UserRole;
          capabilities?: UserCapability[];
          ubuntu_score?: number;
          contribution_count?: number;
          stripe_customer_id?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          company?: string | null;
          country?: string | null;
          role?: UserRole;
          capabilities?: UserCapability[];
          ubuntu_score?: number;
          contribution_count?: number;
          stripe_customer_id?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [];
      };
      /**
       * Activity logs table - Audit trail for user actions
       */
      activity_logs: {
        Row: {
          id: string;
          user_id: string | null;
          activity: ActivityType;
          ip_address: string | null;
          user_agent: string | null;
          metadata: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          activity: ActivityType;
          ip_address?: string | null;
          user_agent?: string | null;
          metadata?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          activity?: ActivityType;
          ip_address?: string | null;
          user_agent?: string | null;
          metadata?: Json | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'activity_logs_user_id_fkey';
            columns: ['user_id'];
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          }
        ];
      };
      directory_listings: {
        Row: {
          id: string;
          user_id: string;
          business_name: string;
          business_type: string;
          category: string;
          country: string;
          city: string | null;
          description: string;
          contact_info: Json;
          media_urls: string[];
          status: ListingStatus;
          verification_status: VerificationStatus;
          verification_fee_paid: boolean;
          reviewed_by: string | null;
          view_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          business_name: string;
          business_type: string;
          category: string;
          country: string;
          city?: string | null;
          description: string;
          contact_info?: Json;
          media_urls?: string[];
          status?: ListingStatus;
          verification_status?: VerificationStatus;
          verification_fee_paid?: boolean;
          reviewed_by?: string | null;
          view_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          business_name?: string;
          business_type?: string;
          category?: string;
          country?: string;
          city?: string | null;
          description?: string;
          contact_info?: Json;
          media_urls?: string[];
          status?: ListingStatus;
          verification_status?: VerificationStatus;
          verification_fee_paid?: boolean;
          reviewed_by?: string | null;
          view_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'directory_listings_user_id_fkey';
            columns: ['user_id'];
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          }
        ];
      };
      content_submissions: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          slug: string | null;
          content: string;
          content_type: string;
          category: string;
          tags: string[];
          featured_image_url: string | null;
          status: ContentStatus;
          reviewed_by: string | null;
          published_at: string | null;
          ubuntu_points_awarded: number;
          view_count: number;
          ai_analysis: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          slug?: string | null;
          content: string;
          content_type: string;
          category: string;
          tags?: string[];
          featured_image_url?: string | null;
          status?: ContentStatus;
          reviewed_by?: string | null;
          published_at?: string | null;
          ubuntu_points_awarded?: number;
          view_count?: number;
          ai_analysis?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          slug?: string | null;
          content?: string;
          content_type?: string;
          category?: string;
          tags?: string[];
          featured_image_url?: string | null;
          status?: ContentStatus;
          reviewed_by?: string | null;
          published_at?: string | null;
          ubuntu_points_awarded?: number;
          view_count?: number;
          ai_analysis?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'content_submissions_user_id_fkey';
            columns: ['user_id'];
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          }
        ];
      };
      ubuntu_contributions: {
        Row: {
          id: string;
          user_id: string;
          contribution_type: string;
          contribution_details: string | null;
          ubuntu_points_earned: number;
          metadata: Json | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          contribution_type: string;
          contribution_details?: string | null;
          ubuntu_points_earned: number;
          metadata?: Json | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          contribution_type?: string;
          contribution_details?: string | null;
          ubuntu_points_earned?: number;
          metadata?: Json | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'ubuntu_contributions_user_id_fkey';
            columns: ['user_id'];
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          }
        ];
      };
      verification_requests: {
        Row: {
          id: string;
          listing_id: string;
          user_id: string;
          stripe_payment_intent_id: string | null;
          payment_status: string;
          payment_amount: number;
          documents: Json | null;
          status: string;
          reviewed_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          listing_id: string;
          user_id: string;
          stripe_payment_intent_id?: string | null;
          payment_status?: string;
          payment_amount?: number;
          documents?: Json | null;
          status?: string;
          reviewed_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          listing_id?: string;
          user_id?: string;
          stripe_payment_intent_id?: string | null;
          payment_status?: string;
          payment_amount?: number;
          documents?: Json | null;
          status?: string;
          reviewed_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'verification_requests_user_id_fkey';
            columns: ['user_id'];
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'verification_requests_listing_id_fkey';
            columns: ['listing_id'];
            referencedRelation: 'directory_listings';
            referencedColumns: ['id'];
          }
        ];
      };
      product_subscriptions: {
        Row: {
          id: string;
          user_id: string;
          product_slug: string;
          stripe_subscription_id: string;
          plan_name: string;
          billing_cycle: string;
          price: number;
          status: SubscriptionStatus;
          current_period_start: string;
          current_period_end: string;
          cancel_at_period_end: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          product_slug: string;
          stripe_subscription_id: string;
          plan_name: string;
          billing_cycle: string;
          price: number;
          status?: SubscriptionStatus;
          current_period_start: string;
          current_period_end: string;
          cancel_at_period_end?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          product_slug?: string;
          stripe_subscription_id?: string;
          plan_name?: string;
          billing_cycle?: string;
          price?: number;
          status?: SubscriptionStatus;
          current_period_start?: string;
          current_period_end?: string;
          cancel_at_period_end?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'product_subscriptions_user_id_fkey';
            columns: ['user_id'];
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          }
        ];
      };
      travel_businesses: {
        Row: {
          id: string;
          owner_id: string;
          business_name: string;
          business_type: string;
          description: string | null;
          country: string;
          city: string | null;
          address: string | null;
          phone: string | null;
          email: string | null;
          website: string | null;
          services: string | null;
          specialties: string | null;
          status: ListingStatus;
          verification_status: VerificationStatus;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          owner_id: string;
          business_name: string;
          business_type: string;
          description?: string | null;
          country: string;
          city?: string | null;
          address?: string | null;
          phone?: string | null;
          email?: string | null;
          website?: string | null;
          services?: string | null;
          specialties?: string | null;
          status?: ListingStatus;
          verification_status?: VerificationStatus;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          owner_id?: string;
          business_name?: string;
          business_type?: string;
          description?: string | null;
          country?: string;
          city?: string | null;
          address?: string | null;
          phone?: string | null;
          email?: string | null;
          website?: string | null;
          services?: string | null;
          specialties?: string | null;
          status?: ListingStatus;
          verification_status?: VerificationStatus;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'travel_businesses_owner_id_fkey';
            columns: ['owner_id'];
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          }
        ];
      };
      /**
       * ZTI Experts table - Local guides and specialists
       */
      experts: {
        Row: {
          id: string;
          full_name: string;
          email: string;
          phone: string;
          location: string;
          category: ExpertCategory;
          years_experience: string;
          certifications: string;
          languages: string;
          services: string;
          bio: string | null;
          motivation: string | null;
          website: string | null;
          profile_image: string | null;
          status: ApplicationStatus;
          verified: boolean;
          featured: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          full_name: string;
          email: string;
          phone: string;
          location: string;
          category: ExpertCategory;
          years_experience: string;
          certifications: string;
          languages: string;
          services: string;
          bio?: string | null;
          motivation?: string | null;
          website?: string | null;
          profile_image?: string | null;
          status?: ApplicationStatus;
          verified?: boolean;
          featured?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string;
          email?: string;
          phone?: string;
          location?: string;
          category?: ExpertCategory;
          years_experience?: string;
          certifications?: string;
          languages?: string;
          services?: string;
          bio?: string | null;
          motivation?: string | null;
          website?: string | null;
          profile_image?: string | null;
          status?: ApplicationStatus;
          verified?: boolean;
          featured?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      /**
       * ZTI Businesses table - Business partner directory
       */
      businesses: {
        Row: {
          id: string;
          business_name: string;
          contact_person: string;
          email: string;
          phone: string;
          website: string | null;
          category: string;
          subcategory: string | null;
          location: string;
          description: string;
          target_travelers: string | null;
          listing_type: ListingType;
          promotion_interest: boolean;
          status: ApplicationStatus;
          verified: boolean;
          featured: boolean;
          logo_url: string | null;
          images: string[];
          amenities: string[];
          price_range: string | null;
          rating: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          business_name: string;
          contact_person: string;
          email: string;
          phone: string;
          website?: string | null;
          category: string;
          subcategory?: string | null;
          location: string;
          description: string;
          target_travelers?: string | null;
          listing_type?: ListingType;
          promotion_interest?: boolean;
          status?: ApplicationStatus;
          verified?: boolean;
          featured?: boolean;
          logo_url?: string | null;
          images?: string[];
          amenities?: string[];
          price_range?: string | null;
          rating?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          business_name?: string;
          contact_person?: string;
          email?: string;
          phone?: string;
          website?: string | null;
          category?: string;
          subcategory?: string | null;
          location?: string;
          description?: string;
          target_travelers?: string | null;
          listing_type?: ListingType;
          promotion_interest?: boolean;
          status?: ApplicationStatus;
          verified?: boolean;
          featured?: boolean;
          logo_url?: string | null;
          images?: string[];
          amenities?: string[];
          price_range?: string | null;
          rating?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      /**
       * Unified submissions table - Central pipeline for all submissions
       * Provides a unified view of content, expert, and business submissions
       */
      unified_submissions: {
        Row: {
          id: string;
          user_id: string;
          submission_type: SubmissionType;
          reference_id: string;
          title: string;
          description: string | null;
          status: PipelineStatus;
          assigned_to: string | null;
          reviewer_notes: string | null;
          submitted_at: string | null;
          reviewed_at: string | null;
          published_at: string | null;
          metadata: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          submission_type: SubmissionType;
          reference_id: string;
          title: string;
          description?: string | null;
          status?: PipelineStatus;
          assigned_to?: string | null;
          reviewer_notes?: string | null;
          submitted_at?: string | null;
          reviewed_at?: string | null;
          published_at?: string | null;
          metadata?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          submission_type?: SubmissionType;
          reference_id?: string;
          title?: string;
          description?: string | null;
          status?: PipelineStatus;
          assigned_to?: string | null;
          reviewer_notes?: string | null;
          submitted_at?: string | null;
          reviewed_at?: string | null;
          published_at?: string | null;
          metadata?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'unified_submissions_user_id_fkey';
            columns: ['user_id'];
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'unified_submissions_assigned_to_fkey';
            columns: ['assigned_to'];
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          }
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      increment_ubuntu_score: {
        Args: {
          user_id: string;
          points: number;
        };
        Returns: Database['public']['Tables']['profiles']['Row'];
      };
      get_top_contributors: {
        Args: {
          row_limit: number;
        };
        Returns: {
          userId: string;
          totalPoints: number;
          contributionCount: number;
        }[];
      };
    };
    Enums: {
      user_role: UserRole;
      user_capability: UserCapability;
      submission_type: SubmissionType;
      pipeline_status: PipelineStatus;
      listing_status: ListingStatus;
      content_status: ContentStatus;
      verification_status: VerificationStatus;
      subscription_status: SubscriptionStatus;
      application_status: ApplicationStatus;
      listing_type: ListingType;
      expert_category: ExpertCategory;
      activity_type: ActivityType;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}
