/**
 * 🇿🇼 Nyuchi Platform - Database Types
 * "I am because we are"
 *
 * These types will be generated by Supabase CLI once migrations are run.
 * For now, we define the core structure manually.
 */

/**
 * User role enum
 */
export type UserRole = 'user' | 'contributor' | 'moderator' | 'admin';

/**
 * Listing status enum
 */
export type ListingStatus = 'draft' | 'pending' | 'approved' | 'rejected' | 'published';

/**
 * Content status enum
 */
export type ContentStatus = 'draft' | 'submitted' | 'reviewing' | 'approved' | 'rejected' | 'published';

/**
 * Verification status enum
 */
export type VerificationStatus = 'none' | 'pending' | 'approved' | 'rejected';

/**
 * Subscription status enum
 */
export type SubscriptionStatus = 'active' | 'canceled' | 'past_due' | 'trialing' | 'incomplete';

/**
 * Database tables
 */
export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string | null;
          avatar_url: string | null;
          company: string | null;
          country: string | null;
          role: UserRole;
          ubuntu_score: number;
          contribution_count: number;
          stripe_customer_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          full_name?: string | null;
          avatar_url?: string | null;
          company?: string | null;
          country?: string | null;
          role?: UserRole;
          ubuntu_score?: number;
          contribution_count?: number;
          stripe_customer_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          company?: string | null;
          country?: string | null;
          role?: UserRole;
          ubuntu_score?: number;
          contribution_count?: number;
          stripe_customer_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      directory_listings: {
        Row: {
          id: string;
          user_id: string;
          business_name: string;
          business_type: string;
          category: string;
          country: string;
          city: string | null;
          description: string;
          contact_info: Record<string, any>;
          media_urls: string[];
          status: ListingStatus;
          verification_status: VerificationStatus;
          verification_fee_paid: boolean;
          reviewed_by: string | null;
          view_count: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          business_name: string;
          business_type: string;
          category: string;
          country: string;
          city?: string | null;
          description: string;
          contact_info?: Record<string, any>;
          media_urls?: string[];
          status?: ListingStatus;
          verification_status?: VerificationStatus;
          verification_fee_paid?: boolean;
          reviewed_by?: string | null;
          view_count?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          business_name?: string;
          business_type?: string;
          category?: string;
          country?: string;
          city?: string | null;
          description?: string;
          contact_info?: Record<string, any>;
          media_urls?: string[];
          status?: ListingStatus;
          verification_status?: VerificationStatus;
          verification_fee_paid?: boolean;
          reviewed_by?: string | null;
          view_count?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      content_submissions: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          slug: string | null;
          content: string;
          content_type: string;
          category: string;
          tags: string[];
          featured_image_url: string | null;
          status: ContentStatus;
          reviewed_by: string | null;
          published_at: string | null;
          ubuntu_points_awarded: number;
          view_count: number;
          ai_analysis: Record<string, any> | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          slug?: string | null;
          content: string;
          content_type: string;
          category: string;
          tags?: string[];
          featured_image_url?: string | null;
          status?: ContentStatus;
          reviewed_by?: string | null;
          published_at?: string | null;
          ubuntu_points_awarded?: number;
          view_count?: number;
          ai_analysis?: Record<string, any> | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          slug?: string | null;
          content?: string;
          content_type?: string;
          category?: string;
          tags?: string[];
          featured_image_url?: string | null;
          status?: ContentStatus;
          reviewed_by?: string | null;
          published_at?: string | null;
          ubuntu_points_awarded?: number;
          view_count?: number;
          ai_analysis?: Record<string, any> | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      ubuntu_contributions: {
        Row: {
          id: string;
          user_id: string;
          contribution_type: string;
          contribution_details: string | null;
          ubuntu_points_earned: number;
          metadata: Record<string, any> | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          contribution_type: string;
          contribution_details?: string | null;
          ubuntu_points_earned: number;
          metadata?: Record<string, any> | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          contribution_type?: string;
          contribution_details?: string | null;
          ubuntu_points_earned?: number;
          metadata?: Record<string, any> | null;
          created_at?: string;
        };
      };
      verification_requests: {
        Row: {
          id: string;
          listing_id: string;
          user_id: string;
          stripe_payment_intent_id: string | null;
          payment_status: string;
          payment_amount: number;
          documents: Record<string, any> | null;
          status: string;
          reviewed_by: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          listing_id: string;
          user_id: string;
          stripe_payment_intent_id?: string | null;
          payment_status?: string;
          payment_amount?: number;
          documents?: Record<string, any> | null;
          status?: string;
          reviewed_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          listing_id?: string;
          user_id?: string;
          stripe_payment_intent_id?: string | null;
          payment_status?: string;
          payment_amount?: number;
          documents?: Record<string, any> | null;
          status?: string;
          reviewed_by?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      product_subscriptions: {
        Row: {
          id: string;
          user_id: string;
          product_slug: string;
          stripe_subscription_id: string;
          plan_name: string;
          billing_cycle: string;
          price: number;
          status: SubscriptionStatus;
          current_period_start: string;
          current_period_end: string;
          cancel_at_period_end: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          product_slug: string;
          stripe_subscription_id: string;
          plan_name: string;
          billing_cycle: string;
          price: number;
          status?: SubscriptionStatus;
          current_period_start: string;
          current_period_end: string;
          cancel_at_period_end?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          product_slug?: string;
          stripe_subscription_id?: string;
          plan_name?: string;
          billing_cycle?: string;
          price?: number;
          status?: SubscriptionStatus;
          current_period_start?: string;
          current_period_end?: string;
          cancel_at_period_end?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
}
